# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VoxOIhqIkGTWMR1g1l_PzGRYhKOjTUcl
"""

pip install newspaper3k

from newspaper import Article
import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings
warnings.filterwarnings('ignore')

#download punkt package
nltk.download('punkt', quiet=True)

#Article
article = Article('https://es.wikipedia.org/wiki/Cannabis_sativa')
article.download()
article.parse()
article.nlp()
corpus = article.text

print(corpus)

#Tokenization
text = corpus
sentence_list = nltk.sent_tokenize(text) #Lista of sentences

def greeting_response(text):
  text = text.lower()

  #Bots greeting response
  bot_greetings = ['hey', 'hello', 'que onda mi rey', 'hola rey']
  #user greetin
  user_greetings = ['hola', 'hello', 'hi', 'holis']

  for word in text.split():
    if word in user_greetings:
      return random.choice(bot_greetings)

def index_sort(list_var):
  length = len(list_var)
  list_index = list(range(0, lenght))

  x = list_var
  for i in range(length):
    for j in range(length):
      if x[list_index[i]] > x[list_index[j]]:
        #Swap
        temp = list_index[i]
        list_index[i] = list_index[j]
        list_index[j] = temp
  return list_index

#Bot Response
def bot_response(user_input):
  user_input = user_input_lower()
  sentence_list.append(user_input)
  bot_response = ''
  cm = CountVectorizer().fit_transform(sentence_list)
  similarity_scores = cosine_similarity(cm[-1], cm)
  similarity_scores_list = similarity_scores.flatten()
  index = index_sort(similarity_scores_list)
  index = index[1:]
  response_flag = 0

  j = 0
  for i in range(len(index)):
    if similarity_scores_list[index[i]] > 0.0:
      bot_response = bot_response+''+sentence_list[index[i]]
      reponse_flag = 1
      j = j+1
      if j > 2:
        break
  if response_flag == 0:
    bot_response = bot_response+''+"Perdon no entiendo"

  sentence_list.remove(user_input)
  return bot_response

#Start Chat
print('Hola, soy el baby paul de la marihuana sativa, que quieres saber? ')

exit_list = ['exit', 'bye', 'nos re vimos', 'chau', 'chao', 'adios']


while(True):
  user_input = input()
  if user_input.lower() in exit_list:
    print('Baby Paul: Nos vemos rey')
    break
  else:
    if greeting_response(user_input) != None:
      print('Baby Paul: '+greeting_response(user_input))
    else:
      print('Baby Paul: '+bot_response(user_input))



